import { createHash } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { LibraryRef } from '../api/web-client.js';
import type { ToolContext } from '../registry/registry.js';

const PREFIX = 'AI4S-Metrics:';
const SHA256 = /^[0-9a-f]{64}$/;
type Action = { item_key:string; expected_version:number|null; title:string; decision:'update'|'skip'; reason_codes:string[]; citation:Record<string, unknown>|null };
export interface CitationPlan { schema_version:'1.0'; plan_type:'zotero-citations'; created_at:string; plan_hash:string; target:{library_type:'user'|'group';library_id:number}; citation_source:{provider:'semantic-scholar';source_sha256:string}; actions:Action[]; summary:{selected:number;update:number;skip:number}; }
function obj(value:unknown): value is Record<string, any> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function sort(value:any):any { if (Array.isArray(value)) return value.map(sort); if (!obj(value)) return value; return Object.fromEntries(Object.keys(value).sort().map(k => [k, sort(value[k])])); }
export function canonicalCitationPlanHash(plan:CitationPlan):string { const payload={schema_version:plan.schema_version,plan_type:plan.plan_type,target:plan.target,citation_source:plan.citation_source,actions:[...plan.actions].sort((a,b)=>a.item_key.localeCompare(b.item_key))}; return `sha256:${createHash('sha256').update(JSON.stringify(sort(payload))).digest('hex')}`; }
function validCitation(value:any):boolean { return obj(value) && Number.isInteger(value.citation_count) && value.citation_count >= 0 && value.provider === 'semantic-scholar' && /^\d{4}-\d{2}-\d{2}$/.test(String(value.retrieved_at)) && SHA256.test(String(value.source_sha256)); }
export function validateCitationPlan(value:unknown):CitationPlan {
  if (!obj(value) || value.schema_version !== '1.0' || value.plan_type !== 'zotero-citations' || !/^sha256:[0-9a-f]{64}$/.test(String(value.plan_hash))) throw new Error('Unsupported or invalid citation plan');
  if (!obj(value.target) || !['user','group'].includes(value.target.library_type) || !Number.isInteger(value.target.library_id) || !obj(value.citation_source) || value.citation_source.provider !== 'semantic-scholar' || !SHA256.test(String(value.citation_source.source_sha256)) || !Array.isArray(value.actions) || !obj(value.summary)) throw new Error('Invalid citation plan contract');
  const keys=new Set<string>(); for (const action of value.actions) { if (!obj(action) || !action.item_key || keys.has(action.item_key) || !['update','skip'].includes(action.decision) || !Array.isArray(action.reason_codes)) throw new Error('Invalid citation plan action'); keys.add(action.item_key); if (action.decision === 'update' && (!Number.isInteger(action.expected_version) || !validCitation(action.citation))) throw new Error(`Invalid citation update ${action.item_key}`); }
  const expected={selected:value.actions.length,update:value.actions.filter((a:any)=>a.decision==='update').length,skip:value.actions.filter((a:any)=>a.decision==='skip').length}; if (Object.entries(expected).some(([k,n])=>value.summary[k]!==n)) throw new Error('Citation plan summary does not match actions');
  const plan=value as CitationPlan; if (canonicalCitationPlanHash(plan)!==plan.plan_hash) throw new Error('Citation plan hash mismatch'); return plan;
}
export async function readCitationPlan(path:string):Promise<CitationPlan>{ return validateCitationPlan(JSON.parse(await readFile(path,'utf8'))); }
function parse(extra:unknown):Record<string,any>|null { const lines=String(extra??'').split(/\r?\n/); const matches=lines.filter(line=>line.startsWith(PREFIX)); if (!matches.length) return {schema_version:2,by_year:{}}; if (matches.length!==1) return null; try { const payload=JSON.parse(matches[0]!.slice(PREFIX.length).trim()); return obj(payload)&&payload.schema_version===2&&obj(payload.by_year)?payload:null; } catch { return null; } }
function merge(extra:unknown,citation:Record<string,unknown>):string|null { const payload=parse(extra); if (!payload) return null; const latest=payload.citation?.latest; const history=Array.isArray(payload.citation?.history)?payload.citation.history.filter(validCitation):[]; if (validCitation(latest) && JSON.stringify(sort(latest))!==JSON.stringify(sort(citation))) history.push(latest); payload.citation={latest:citation,history:[...history, citation].filter((entry,index,all)=>all.findIndex(other=>other.retrieved_at===entry.retrieved_at&&other.citation_count===entry.citation_count)===index).slice(-12)}; const retained=String(extra??'').split(/\r?\n/).filter(line=>!line.startsWith(PREFIX)); return [...retained,`${PREFIX} ${JSON.stringify(sort(payload))}`].filter(Boolean).join('\n'); }
function data(item:any):Record<string,any>{return obj(item?.data)?item.data:item??{};} function version(item:any):number|null{const v=item?.version??item?.data?.version;return Number.isInteger(v)?v:null;}
type Outcome='updated'|'unchanged'|'skipped'|'failed'|'pending'; type Receipt={schema_version:'1.0';receipt_type:'zotero-citations';plan_hash:string;status:'complete'|'partial'|'blocked';started_at:string;updated_at:string;results:Array<{item_key:string;outcome:Outcome;zotero_version:number|null;error:string|null}>;summary:Record<Outcome,number>};
function summarize(receipt:Receipt){for(const k of ['updated','unchanged','skipped','failed','pending'] as const)receipt.summary[k]=receipt.results.filter(r=>r.outcome===k).length;receipt.updated_at=new Date().toISOString();receipt.status=receipt.summary.pending?'blocked':receipt.summary.failed?'partial':'complete';}
function initial(plan:CitationPlan):Receipt{const now=new Date().toISOString();const receipt:Receipt={schema_version:'1.0',receipt_type:'zotero-citations',plan_hash:plan.plan_hash,status:'partial',started_at:now,updated_at:now,results:plan.actions.map(a=>({item_key:a.item_key,outcome:a.decision==='skip'?'skipped':'pending',zotero_version:a.expected_version,error:a.decision==='skip'?a.reason_codes.join(';'):null})),summary:{updated:0,unchanged:0,skipped:0,failed:0,pending:0}};summarize(receipt);return receipt;}
async function persist(path:string,receipt:Receipt){summarize(receipt);await mkdir(dirname(path),{recursive:true});const temp=`${path}.tmp-${process.pid}`;await writeFile(temp,`${JSON.stringify(receipt,null,2)}\n`);await rename(temp,path);}
export async function executeCitationPlan(ctx:ToolContext,plan:CitationPlan,lib:LibraryRef,mode:'dry_run'|'apply',receiptPath?:string){let receipt=initial(plan);if(mode==='apply'&&receiptPath){try{const old=JSON.parse(await readFile(receiptPath,'utf8')) as Receipt;if(old.plan_hash!==plan.plan_hash)throw new Error('Receipt plan hash does not match');receipt=old;if(old.status==='complete')return {status:'complete',summary:old.summary,receiptPath,conflicts:[]};}catch(e:any){if(e?.code!=='ENOENT')throw e;}}const conflicts:string[]=[];for(const action of plan.actions.filter(a=>a.decision==='update')){const result=receipt.results.find(r=>r.item_key===action.item_key)!;if(result.outcome!=='pending')continue;try{const item=await ctx.web.getItem(lib,action.item_key);const current=version(item);if(current===null||current!==action.expected_version){conflicts.push(action.item_key);result.outcome='failed';result.error='version-conflict';continue;}const extra=merge(data(item).extra,action.citation!);if(!extra){result.outcome='failed';result.error='invalid-or-duplicate-ai4s-metrics-block';continue;}if(extra===String(data(item).extra??'')){result.outcome='unchanged';continue;}if(mode==='dry_run'){result.outcome='pending';continue;}result.zotero_version=await ctx.web.patchItem(lib,action.item_key,{extra},current);result.outcome='updated';result.error=null;}catch(e){result.outcome='failed';result.error=(e instanceof Error?e.message:String(e)).slice(0,500);}}if(mode==='dry_run')return {status:conflicts.length?'blocked':'ready',summary:{...receipt.summary,pending:receipt.results.filter(r=>r.outcome==='pending').length},conflicts};if(!receiptPath)throw new Error('receipt path is required for apply');await persist(receiptPath,receipt);return {status:receipt.status,summary:receipt.summary,receiptPath,conflicts};}
